if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

alias l='ls -CF --color=auto'
alias ll='ls -la --color=auto'
alias ls='ls --color=auto'
alias grep='grep -rn --color=auto'

PS1='${debian_chroot:+($debian_chroot)}\[\033[36;40m\]\u \[\033[1;31;40m\]\w \[\033[1;35;40m\]\$ > \[\033[1;0;0m\]'
